"""tests/test_dep_lock.py — SHP.7 dep lock drift detection.

Tests for rawos.kernel.dep_lock.verify_dep_lock().
All tests inject _pip_freeze_output to avoid real pip invocations.
"""
from __future__ import annotations

import textwrap

import pytest

from anima.kernel.dep_lock import DepDriftResult, verify_dep_lock


_LOCK_CONTENTS = textwrap.dedent("""\
    aiofiles==25.1.0
    httpx==0.27.0
    fastapi==0.115.0
    cryptography==49.0.0
""")


class TestVerifyDepLock:
    def test_no_drift_returns_ok(self, tmp_path):
        lock = tmp_path / "requirements.lock"
        lock.write_text(_LOCK_CONTENTS)
        result = verify_dep_lock(lock_path=lock, _pip_freeze_output=_LOCK_CONTENTS)
        assert result.ok is True
        assert result.added == []
        assert result.removed == []
        assert result.changed == []

    def test_added_package_detected(self, tmp_path):
        lock = tmp_path / "requirements.lock"
        lock.write_text(_LOCK_CONTENTS)
        env_freeze = _LOCK_CONTENTS + "evil-package==0.0.1\n"
        result = verify_dep_lock(lock_path=lock, _pip_freeze_output=env_freeze)
        assert result.ok is False
        assert any("evil_package" in a or "evil-package" in a for a in result.added)

    def test_removed_package_detected(self, tmp_path):
        lock = tmp_path / "requirements.lock"
        lock.write_text(_LOCK_CONTENTS)
        env_freeze = "aiofiles==25.1.0\nhttpx==0.27.0\nfastapi==0.115.0\n"  # cryptography removed
        result = verify_dep_lock(lock_path=lock, _pip_freeze_output=env_freeze)
        assert result.ok is False
        assert any("cryptography" in r for r in result.removed)

    def test_version_change_detected(self, tmp_path):
        lock = tmp_path / "requirements.lock"
        lock.write_text(_LOCK_CONTENTS)
        env_freeze = "aiofiles==25.1.0\nhttpx==0.99.0\nfastapi==0.115.0\ncryptography==49.0.0\n"
        result = verify_dep_lock(lock_path=lock, _pip_freeze_output=env_freeze)
        assert result.ok is False
        assert any("httpx" in c for c in result.changed)
        assert any("0.27.0" in c and "0.99.0" in c for c in result.changed)

    def test_missing_lock_file_returns_not_ok(self, tmp_path):
        lock = tmp_path / "nonexistent.lock"
        result = verify_dep_lock(lock_path=lock, _pip_freeze_output=_LOCK_CONTENTS)
        assert result.ok is False
        assert result.changed  # contains error message about missing file

    def test_summary_ok(self, tmp_path):
        lock = tmp_path / "requirements.lock"
        lock.write_text(_LOCK_CONTENTS)
        result = verify_dep_lock(lock_path=lock, _pip_freeze_output=_LOCK_CONTENTS)
        assert result.summary == "dep lock OK"

    def test_summary_drift(self, tmp_path):
        lock = tmp_path / "requirements.lock"
        lock.write_text(_LOCK_CONTENTS)
        env_freeze = _LOCK_CONTENTS + "evil-package==0.0.1\n"
        result = verify_dep_lock(lock_path=lock, _pip_freeze_output=env_freeze)
        assert "added" in result.summary

    def test_comments_and_blank_lines_ignored(self, tmp_path):
        lock_with_comments = "# Generated by pip freeze\naiofiles==25.1.0\n\nhttpx==0.27.0\n"
        env_freeze = "aiofiles==25.1.0\nhttpx==0.27.0\n"
        lock = tmp_path / "requirements.lock"
        lock.write_text(lock_with_comments)
        result = verify_dep_lock(lock_path=lock, _pip_freeze_output=env_freeze)
        assert result.ok is True

    def test_package_name_normalisation_dash_underscore(self, tmp_path):
        """pip freeze may use hyphens; internal normalisation must treat them as underscores."""
        lock = tmp_path / "requirements.lock"
        lock.write_text("some-package==1.0.0\n")
        env_freeze = "some_package==1.0.0\n"
        result = verify_dep_lock(lock_path=lock, _pip_freeze_output=env_freeze)
        assert result.ok is True

    def test_result_is_frozen_dataclass(self, tmp_path):
        lock = tmp_path / "requirements.lock"
        lock.write_text(_LOCK_CONTENTS)
        result = verify_dep_lock(lock_path=lock, _pip_freeze_output=_LOCK_CONTENTS)
        with pytest.raises((AttributeError, TypeError)):
            result.ok = False  # type: ignore[misc]
